---

- name: Copy helper scripts for fmn-frontend
  copy:
    src: '{{item}}'
    dest: '/home/vagrant/.local/bin/'
    owner: vagrant
    group: vagrant
    mode: 0744
  loop:
    - fmn-frontend-logs
    - fmn-frontend-restart
    - fmn-frontend-start
    - fmn-frontend-status
    - fmn-frontend-stop

- name: Install the systemd unit files for the fmn-frontend service
  copy:
      src: fmn-frontend.service
      dest: /etc/systemd/system/fmn-frontend.service
      mode: 0644

- name: install the frontend with npm
  command: npm install
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/fmn/frontend

- name: Start the service using systemd
  systemd:
    state: started
    name: fmn-frontend
    daemon_reload: yes
    enabled: yes
