---
- name: Install RPM packages
  dnf:
      name:
        - git
        - vim
        - poetry
        - python3-pip
        - python3-devel
        - fedora-messaging
        - npm
      state: present


- name: Install the .bashrc
  copy:
      src: bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

# running npm from systemd causes some selinux issues -- turn it off for now
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: Install the systemd unit files for the fmn-frontend service
  copy:
      src: fmn-frontend.service
      dest: /etc/systemd/system/fmn-frontend.service
      mode: 0644

- name: install the frontend with npm
  command: npm install
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/fmn/frontend


- name: Start the service using systemd
  systemd:
    state: started
    name: fmn-frontend
    daemon_reload: yes
    enabled: yes
